// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageList():Promise<Array<string>>;

export function GetSoundList():Promise<Array<string>>;

export function GetSpriteList():Promise<Array<string>>;

export function LoadStory():Promise<string>;

export function SaveStory(arg1:string):Promise<string>;
