// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageList() {
  return window['go']['main']['App']['GetImageList']();
}

export function GetSoundList() {
  return window['go']['main']['App']['GetSoundList']();
}

export function GetSpriteList() {
  return window['go']['main']['App']['GetSpriteList']();
}

export function LoadStory() {
  return window['go']['main']['App']['LoadStory']();
}

export function SaveStory(arg1) {
  return window['go']['main']['App']['SaveStory'](arg1);
}
